version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: olhar180_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #ports:
    #- '5432:5432'
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres
    restart: always
