version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: meu_postgres
    environment:
      POSTGRES_DB: olhar180_tasklist
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
    restart: always
